version: '3.8'

services:
  java_app:
    container_name: java_app
    image: boris/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
    environment:
      - POSTGRES_HOST=java_db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  java_db:
    image: postgres:latest
    container_name: java_db
    restart: unless-stopped
    environment:
       - POSTGRES_HOST=java_db
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
    postgres:
      driver: bridge
volumes:
  pgdata: {}